### ISSUE TITLE
No Vertex Color imported from 3ds max .abc

### ISSUE THREAD

**Issue by noors84** [unity3d-jp/AlembicForUnity#281] opened 2019-08-14 11:36 UTC
Hi. it looks like the importer ignores vertex color data from Max exports, while Maya files from issue #48 are working. 

Reimporting in Max, the vertex color is there.

Default vertex color channel name in the .abc is Max_Vertex_Color_Map0

- I tried to rename the vertex color channel to rgba, resulting in "Max_Vertex_Color_Maprgba" in the abc. 

- I tried to edit the .abc with a Hex editor to replace with rgba but it doesn't work either.

Is this a known issue, is there a workaround ? Could it be fixed ? This is quite a problem for our project. Thanks !

On a side note, do you kow if it's possible to store and read color data in .abc points cloud (from particles) ?

[boxVC.zip](https://github.com/unity3d-jp/AlembicForUnity/files/3501071/boxVC.zip)

**Comment by clusty** [comment] 2019-08-14 13:16
Hey,

Thanks for the bug report. 
I think this is a duplicate of : https://github.com/unity3d-jp/AlembicForUnity/issues/210 , which, if all goes well, will be fixed in version 1.0.6:

Is this the expected result ?: 
![Screen Shot 2019-08-14 at 8 53 07 AM](https://user-images.githubusercontent.com/328523/63023753-b5ac5f80-be73-11e9-8a30-8b8938061da1.png)

In the currently released version only RGB colours are read.
For the particle colours, I'd have to look into it.

**Comment by noors84** [comment] 2019-08-14 13:33
Thanks. Yes this is the expected result. 
Does it mean the next version will also support vertex alpha ? 
Do you have roughly a release date ? 
Thanks a lot.

**Comment by clusty** [comment] 2019-08-14 13:57
I don't have an exact release date. it's in the process of passing QA validations to make sure it's up to par.
If you need this urgently, you could build your own package (code is in the FTV-97*** branch). Alternatively I could send you a custom build.
Bare in mind this fix has undergone limited testingand you are signing in blood that you understand the risks involved :)

**Comment by noors84** [comment] 2019-08-19 14:51
Ok thanks. I'll use uv channels and a texture map for now.

**Comment by noors84** [comment] 2019-08-23 13:01
Hi clusty. If you don't mind, i would like you to send me a custom build, please. I need extra data and i'd like to avoid using a 2nd uv channel. Thanks.

**Comment by noors84** [comment] 2019-08-28 11:38
Ok thanks a lot. It's working for correctly RGB. 
As soon as i have vertex alpha channel data, the importer interprets it as RGB, overriding the real vertex color values and the vertex alpha is just pure white.

**Comment by noors84** [comment] 2019-08-29 17:42
Yes!
Left cube has vertex color and no vertex alpha.
Right cube has (the same) vertex color + vertex alpha.
I send you a .abc and a fbx.
The fbx acts correctly but not the abc.
Thanks.

![max_cubes](https://user-images.githubusercontent.com/54104590/63963321-0edfda00-ca95-11e9-9e8a-610175875cfd.jpg)
![unity_cubes](https://user-images.githubusercontent.com/54104590/63963327-11daca80-ca95-11e9-8d9d-45157ff76220.jpg)
[VC.zip](https://github.com/unity3d-jp/AlembicForUnity/files/3556748/VC.zip)

**Comment by clusty** [comment] 2019-09-06 17:42
I took some time to look at your files:
running **abcls -vrmla VC/VC_Cubes.ABC** on your files, I get 2 colour channels: /Cube_VC_VA/Cube_VC_VA/Max_Vertex_Color_Map0: which is float3(RGB) /Cube_VC_VA/Cube_VC_VA/Max_Vertex_Color_Map-2: which is float3, but has only the alpha.

The alembic importer is looking for IC4fGeomParam or IC3fGeomParam channels and does not care about the channel name as it's not standard. Your alpha channel is effectively overwriting the RGB, which explains what we are noticing.
Is it possible to export as RGB instead of 2 channels ?

**Comment by noors84** [comment] 2019-09-09 15:18
Yes I can use RGB + extra UV channel to store whatever (noise in my case). Vertex alpha isn't vital for the project.
In Max vertex alpha is a different channel than vertex color. 
So either it's Max alembic exporter which is faulty for not exporting as float4, or it is Unity importer that needs some more instructions to deal particularly with Max export.
Thanks for your time anyway.

**Comment by cguer** [comment] 2019-10-09 17:08
Closing issue as duplicate of https://github.com/unity3d-jp/AlembicForUnity/issues/210

**Closed by cguer** 2019-10-09 17:08 UTC
